#!/usr/bin/env python3
"""Fix the venv so `uv run lit` can import the lit package.

Root cause on macOS + this Python build:
  site.py skips any .pth file with the UF_HIDDEN chflag set
  ("Skipping hidden .pth file"). uv/setuptools editable installs drop
  `__editable__.*.pth` files that often inherit UF_HIDDEN under
  ~/Documents, so the editable install is silently ignored and
  `from lit.cli import main` fails with ModuleNotFoundError.

This script:
  1. Clears UF_HIDDEN on all site-packages/*.pth files
  2. Writes a non-editable path .pth pointing at the project root
  3. Writes sitecustomize.py as a final fallback
"""
from __future__ import annotations

import os
import stat
import sys
from pathlib import Path


SITECUSTOMIZE = '''\
"""Auto-generated by packaging/ensure_sitecustomize.py — do not edit."""
from __future__ import annotations

import sys
from pathlib import Path

def _ensure_project_on_path() -> None:
    try:
        root = Path(sys.prefix).resolve().parent
        if not (root / "lit" / "__init__.py").is_file():
            return
        s = str(root)
        if s not in sys.path:
            sys.path.insert(0, s)
    except Exception:
        pass

_ensure_project_on_path()
'''


def _site_packages() -> Path | None:
    for p in sys.path:
        if p.endswith("site-packages"):
            return Path(p)
    # Fall back to venv layout
    cand = Path(sys.prefix) / "lib" / f"python{sys.version_info.major}.{sys.version_info.minor}" / "site-packages"
    return cand if cand.is_dir() else None


def _clear_hidden(path: Path) -> bool:
    try:
        st = os.lstat(path)
        flags = getattr(st, "st_flags", 0)
        if flags & stat.UF_HIDDEN:
            os.chflags(path, flags & ~stat.UF_HIDDEN)
            return True
    except Exception:
        pass
    return False


def main() -> int:
    sp = _site_packages()
    if sp is None:
        print("No site-packages directory found", file=sys.stderr)
        return 1

    cleared = 0
    for pth in sp.glob("*.pth"):
        if _clear_hidden(pth):
            cleared += 1
            print(f"Cleared UF_HIDDEN on {pth.name}")

    root = Path(sys.prefix).resolve().parent
    if (root / "lit" / "__init__.py").is_file():
        path_pth = sp / "local_issue_tracker_path.pth"
        path_pth.write_text(str(root) + "\n", encoding="utf-8")
        _clear_hidden(path_pth)
        # Newly written files can still pick up UF_HIDDEN under Documents
        try:
            os.chflags(path_pth, 0)
        except Exception:
            pass
        print(f"Wrote {path_pth.name} -> {root}")

    sc = sp / "sitecustomize.py"
    sc.write_text(SITECUSTOMIZE, encoding="utf-8")
    try:
        os.chflags(sc, 0)
    except Exception:
        pass
    print(f"Wrote {sc}")

    # Verify
    try:
        import importlib
        importlib.invalidate_caches()
        # New process would be needed for sitecustomize; check path pth content
        print("Done. Try: uv run lit --version")
    except Exception as e:
        print(f"Note: {e}")
    return 0


if __name__ == "__main__":
        raise SystemExit(main())
